package com.petopia.db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 * Database utility: initialize H2 schema on first use and provide connection.
 */
public class DatabaseUtil {

    // H2 in-memory (shared within same JVM with the same name)
    private static final String H2_URL = "jdbc:h2:mem:petopia;DB_CLOSE_DELAY=-1;MODE=PostgreSQL";
    private static final String H2_USER = "sa";
    private static final String H2_PASSWORD = "";

    // Flag to avoid re-initializing multiple times
    private static volatile boolean initialized = false;

    /**
     * Initialize DB schema and sample data. Safe to call multiple times.
     */
    public static synchronized void initH2() {
        if (initialized) return;

        try (Connection conn = DriverManager.getConnection(H2_URL, H2_USER, H2_PASSWORD);
             Statement st = conn.createStatement()) {

            // ===== USERS TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS users (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "username VARCHAR(100) NOT NULL UNIQUE, " +
                    "password_hash VARCHAR(255), " +
                    "display_name VARCHAR(200), " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP " +
                    ");");

            // ===== PETS TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS pets (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "owner_id BIGINT, " +
                    "name VARCHAR(100) NOT NULL, " +
                    "species VARCHAR(100), " +
                    "level INT DEFAULT 1, " +
                    "exp BIGINT DEFAULT 0, " +
                    "max_hp INT NOT NULL, " +
                    "current_hp INT NOT NULL, " +
                    "attack INT NOT NULL, " +
                    "defense INT NOT NULL, " +
                    "image_path VARCHAR(255), " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "CONSTRAINT fk_pets_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE SET NULL " +
                    ");");

            // ===== MOVES TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS moves (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR(100) NOT NULL, " +
                    "power INT DEFAULT 0, " +
                    "accuracy INT DEFAULT 100, " +
                    "pp INT DEFAULT 10, " +
                    "move_type VARCHAR(50), " +
                    "effect VARCHAR(1000) " +
                    ");");

            // ===== PET_MOVES TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS pet_moves (" +
                    "pet_id BIGINT NOT NULL, " +
                    "move_id BIGINT NOT NULL, " +
                    "pp_left INT, " +
                    "PRIMARY KEY (pet_id, move_id), " +
                    "CONSTRAINT fk_pm_pet FOREIGN KEY (pet_id) REFERENCES pets(id) ON DELETE CASCADE, " +
                    "CONSTRAINT fk_pm_move FOREIGN KEY (move_id) REFERENCES moves(id) ON DELETE CASCADE " +
                    ");");

            // ===== ITEMS TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS items (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "name VARCHAR(100) NOT NULL, " +
                    "item_type VARCHAR(50), " +
                    "effect VARCHAR(1000) " +
                    ");");

            // ===== INVENTORY TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS inventory (" +
                    "owner_id BIGINT NOT NULL, " +
                    "item_id BIGINT NOT NULL, " +
                    "quantity INT DEFAULT 0, " +
                    "PRIMARY KEY (owner_id, item_id), " +
                    "CONSTRAINT fk_inv_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE, " +
                    "CONSTRAINT fk_inv_item FOREIGN KEY (item_id) REFERENCES items(id) ON DELETE CASCADE " +
                    ");");

            // ===== BATTLES TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS battles (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "player_id BIGINT NULL, " +
                    "opponent_name VARCHAR(200), " +
                    "winner VARCHAR(200), " +
                    "duration_ms BIGINT, " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "CONSTRAINT fk_battles_player FOREIGN KEY (player_id) REFERENCES users(id) ON DELETE SET NULL " +
                    ");");

            // ===== BATTLE_LOGS TABLE =====
            st.executeUpdate("CREATE TABLE IF NOT EXISTS battle_logs (" +
                    "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "battle_id BIGINT NOT NULL, " +
                    "turn_index INT NOT NULL, " +
                    "actor VARCHAR(50), " +
                    "action_type VARCHAR(50), " +
                    "value INT, " +
                    "message VARCHAR(1000), " +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "CONSTRAINT fk_bl_battle FOREIGN KEY (battle_id) REFERENCES battles(id) ON DELETE CASCADE " +
                    ");");

            // ===== INDEXES =====
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_pets_owner ON pets(owner_id);");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_battles_player ON battles(player_id);");
            st.executeUpdate("CREATE INDEX IF NOT EXISTS idx_bl_battle ON battle_logs(battle_id);");

            // Insert demo user safely (if not existing)
            try {
                String demoUser = "i19star";
                String demoPass = "password123";
                String demoHash = hashPassword(demoPass);

                try (PreparedStatement check = conn.prepareStatement("SELECT id FROM users WHERE username = ?")) {
                    check.setString(1, demoUser);
                    try (ResultSet rs = check.executeQuery()) {
                        if (!rs.next()) {
                            try (PreparedStatement ins = conn.prepareStatement(
                                    "INSERT INTO users (username, display_name, password_hash) VALUES (?, ?, ?)")) {
                                ins.setString(1, demoUser);
                                ins.setString(2, "Trainer One");
                                ins.setString(3, demoHash);
                                ins.executeUpdate();
                                System.out.println("Inserted demo user: " + demoUser);
                            }
                        } else {
                            System.out.println("Demo user already exists: " + demoUser);
                        }
                    }
                }
            } catch (Exception ex) {
                System.out.println("Could not insert demo user (may already exist): " + ex.getMessage());
            }

            initialized = true;
            System.out.println("✓ H2 Database initialized successfully!");
        } catch (Exception e) {
            System.err.println("✗ Failed to initialize H2 database:");
            e.printStackTrace();
            initialized = false;
        }
    }

    /**
     * Get connection. If not yet initialized, initialize schema first.
     */
    public static Connection getConnection() throws Exception {
        if (!initialized) {
            initH2();
        }
        return DriverManager.getConnection(H2_URL, H2_USER, H2_PASSWORD);
    }

    // Debug helper
    public static void printAllUsers() {
        try (Connection conn = getConnection();
             var st = conn.createStatement();
             var rs = st.executeQuery("SELECT id, username, display_name, created_at FROM users")) {
            System.out.println("=== users table ===");
            while (rs.next()) {
                System.out.printf("%d | %s | %s | %s%n",
                        rs.getLong("id"),
                        rs.getString("username"),
                        rs.getString("display_name"),
                        rs.getTimestamp("created_at"));
            }
        } catch (Exception e) {
            System.err.println("Failed to list users: " + e.getMessage());
        }
    }

    // SHA-256 hash (simple). For production replace with BCrypt.
    public static String hashPassword(String password) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("SHA-256");
            byte[] messageDigest = md.digest(password.getBytes());
            StringBuilder sb = new StringBuilder();
            for (byte b : messageDigest) {
                sb.append(String.format("%02x", b));
            }
            return sb.toString();
        } catch (Exception e) {
            throw new RuntimeException("Error hashing password", e);
        }
    }

    public static boolean verifyPassword(String password, String hash) {
        return hashPassword(password).equals(hash);
    }
}